---
# Source: seldon-core-operator/templates/configmap_seldon-config.yaml
apiVersion: v1
data:
  credentials: '{"gcs":{"gcsCredentialFileName":"gcloud-application-credentials.json"},"s3":{"s3AccessKeyIDName":"awsAccessKeyID","s3SecretAccessKeyName":"awsSecretAccessKey"}}'
  explainer: '{"image":"seldonio/alibiexplainer:1.14.0","image_v2":"seldonio/mlserver:1.1.0-alibi-explain"}'
  predictor_servers: '{"HUGGINGFACE_SERVER":{"protocols":{"v2":{"defaultImageVersion":"1.1.0-huggingface","image":"seldonio/mlserver"}}},"MLFLOW_SERVER":{"protocols":{"seldon":{"defaultImageVersion":"1.14.0","image":"seldonio/mlflowserver"},"v2":{"defaultImageVersion":"1.1.0-mlflow","image":"seldonio/mlserver"}}},"SKLEARN_SERVER":{"protocols":{"seldon":{"defaultImageVersion":"1.14.0","image":"seldonio/sklearnserver"},"v2":{"defaultImageVersion":"1.1.0-sklearn","image":"seldonio/mlserver"}}},"TEMPO_SERVER":{"protocols":{"v2":{"defaultImageVersion":"1.1.0-slim","image":"seldonio/mlserver"}}},"TENSORFLOW_SERVER":{"protocols":{"seldon":{"defaultImageVersion":"1.14.0","image":"seldonio/tfserving-proxy"},"tensorflow":{"defaultImageVersion":"2.1.0","image":"tensorflow/serving"}}},"TRITON_SERVER":{"protocols":{"v2":{"defaultImageVersion":"21.08-py3","image":"nvcr.io/nvidia/tritonserver"}}},"XGBOOST_SERVER":{"protocols":{"seldon":{"defaultImageVersion":"1.14.0","image":"seldonio/xgboostserver"},"v2":{"defaultImageVersion":"1.1.0-xgboost","image":"seldonio/mlserver"}}}}'
  storageInitializer: '{"cpuLimit":"1","cpuRequest":"100m","image":"seldonio/rclone-storage-initializer:1.14.0","memoryLimit":"1Gi","memoryRequest":"100Mi"}'
kind: ConfigMap
metadata:
  labels:
    app: seldon
    app.kubernetes.io/instance: 'release-name'
    app.kubernetes.io/name: 'seldon-core-operator'
    app.kubernetes.io/version: '1.14.0'
    control-plane: seldon-controller-manager
  name: seldon-config
  namespace: 'seldon-system'
